Queue method
millavalio-Unikie/complex-copy pull request #2
Opened 2022-09-22 13:16 UTC by giangle-unikie

2022-09-22 15:24 UTC, LorenzoRuffati requested changes
I will check more in detail tomorrow morning but these are some initial observations

2022-09-22 15:24 UTC, LorenzoRuffati commented on ipc_sendfile.c
> +	while ((opt = getopt(argc, argv, "hf:q:p:s:")) != -1) {
The argument parsing can also be abstracted to its own function common to both files and returning a struct, this would avoid code duplication and simplify bug fixing

2022-09-22 15:24 UTC, LorenzoRuffati commented on ipc_sendfile.c
> +					if (buffer != NULL)
As before, the check if malloc failed should not be inside the loop

2022-09-22 15:24 UTC, LorenzoRuffati commented on ipc_sendfile.c
> +#define MQ_MSGSIZE 8192
Are you sure these values are going to be correct on all systems?

The man page says to use mq_getattr to get the correct limits

2022-09-23 05:50 UTC, LorenzoRuffati commented on ipc_receivefile.c
> +					mq = mq_open(method_name, O_RDONLY, 0666, NULL);
Why don't you just create the queue and then wait until it gets a message instead of waiting for the queue to be created by the writer?

In any case I'd suggest adding a sleep here, even for just half a second every iteration because this loop is just going to cause a disproportionate cpu usage

2022-09-23 05:50 UTC, LorenzoRuffati commented on ipc_sendfile.c
> +				while (send < file_size)
An alternative way to detect the end of the file, which might improve readability by reducing the number of variables is that if you read all the file contents the next call to `read` will return 0, so this would work too:

```suggestion
				while (read(fd, buffer, MQ_MSGSIZE) != 0)
```

2022-09-23 05:50 UTC, LorenzoRuffati commented on ipc_sendfile.c
> +				while (send < file_size)
If instead you want to save the return code in order to account for error handling you could also do:
```suggestion
				while ((ret_code = read(fd, buffer, MQ_MSGSIZE)) != 0)
```

2022-09-23 05:55 UTC, LorenzoRuffati commented on ipc_receivefile.c
> +				fd = open(file_name, O_RDWR,0660);
```suggestion
				fd = open(file_name, O_RDWR | O_CREAT | O_EXCL ,0660);
```
When receiving a file we expect the destination file not to exist

2022-09-23 07:21 UTC, giangle-unikie commented on README.md
> +vv
No, it is not. It is just a mistake that I made when I copy the new update README of Milla

2022-09-23 07:25 UTC, giangle-unikie commented on ipc_receivefile.c
> +void write_to_file(char *data, size_t data_size, long int fd);
Because I only have 2 definitions so I put them in the same file, if I have more, I will make the header file.

2022-09-23 08:09 UTC, giangle-unikie commented on ipc_receivefile.c
> +							write_to_file(data, read_size, fd);
Accept the suggestion. I will do it

2022-09-23 08:30 UTC, LorenzoRuffati commented on ipc_receivefile.c
> +void write_to_file(char *data, size_t data_size, long int fd);
Yeah, my bad ignore this suggestion, it was wrong to begin with because I forgot C scans the source linearly

2022-09-23 08:46 UTC, giangle-unikie commented on ipc_receivefile.c
> +				fd = open(file_name, O_RDWR,0660);
You are right. I will change it as your suggestion

2022-09-23 14:40 UTC, giangle-unikie commented on ipc_receivefile.c
> +				while (error_code != EAGAIN)
mq_receive() only sets errno to EAGAIN when the queue is empty.

2022-09-23 15:36 UTC, giangle-unikie commented on ipc_sendfile.c
> +				while (send < file_size)
Your idea í right, however, if I use ret_code = read(fd, buffer, MQ_MSGSIZE, I still need to declare a variable to get total_send_size so I keep the way I did.

2022-09-26 05:47 UTC, LorenzoRuffati commented on ipc_receivefile.c
> +				while (error_code != EAGAIN)
Yes, but how do you tell the difference between the queue being empty because the sender has terminated and the queue being empty because the sender is taking a long time to send a message and the reader finished reading all the data previously on the queue?

2022-09-27 10:17 UTC, giangle-unikie commented on ipc_receivefile.c
> +				while (error_code != EAGAIN)
Your idea is right, after many tests, I decide to use mq_timedreceive

2022-09-27 10:29 UTC, giangle-unikie commented on ipc_sendfile.c
> +#define MQ_MSGSIZE 8192
The values of MQ_MAXMSG and MQ_MSGSIZE that I set are taken from mq_getattr

2022-09-27 10:38 UTC, LorenzoRuffati commented on ipc_sendfile.c
> +#define MQ_MSGSIZE 8192
what I mean is that those values might change, for instance it's possible (though unlikely) that on ubuntu it's 8192 while on the raspberry pi image generated through yocto this value might be 4096, that's why the documentation says to use mq_getattr at runtime

2022-09-28 05:54 UTC, LorenzoRuffati approved these changes
It would probably work because the read should overwrite existing data in the file, however I think it'd be best if you explicitly handled the case of the output file already existing

2022-09-28 05:54 UTC, LorenzoRuffati commented on ipc_common.c
> +void options(ipc *info, int argc, char *argv[]){
Structs can be returned by value from functions, it's minor since you only use this function once but I'd suggest changing the function signature as follows:
```suggestion
ipc options(int argc, char *argv[]){
```
Then creating the struct inside the function ```ipc info = (ipc) {.file_name=NULL, .method_name=NULL, .fflag=0, .qflag=0, .pflag=0, .sflag=0}```

And simply returning info

2022-09-28 05:54 UTC, LorenzoRuffati commented on ipc_receivefile.c
> +	options(info, argc, argv);
Referring to my comment in ipc_common.c, this could become 
```suggestion
	ipc info = options(argc, argv);
```

2022-09-28 05:54 UTC, LorenzoRuffati commented on ipc_receivefile.c
> +	options(info, argc, argv);
Of course it'd require changing every `->` to a `.` later

2022-09-28 05:54 UTC, LorenzoRuffati commented on ipc_receivefile.c
>  					"./ipcReceive -s <shared_name> -f <file_name>\n");
This could also be part of the options function since it's an error shared by both programs

2022-09-28 05:54 UTC, LorenzoRuffati commented on ipc_receivefile.c
> +		fd = open(info->file_name, O_RDWR | O_CREAT , 0660);
This doesn't check whether the file exists already, can be solved one of two ways:
```suggestion
		fd = open(info->file_name, O_RDWR | O_CREAT | O_EXCL, 0660);
```
to fail if the file exists already

```suggestion
		fd = open(info->file_name, O_RDWR | O_CREAT | O_TRUNC, 0660);
```
to silently delete the file contents if they exist already

2022-09-28 05:54 UTC, LorenzoRuffati commented on ipc_receivefile.c
> +						if (errno == 110) /* Timeout error */
I would suggest using the error name here instead of 110 (improves readability), I presume it'd be `ETIMEDOUT`?

2022-09-28 05:54 UTC, LorenzoRuffati commented on ipc_sendfile.c
>  					if (buffer != NULL)
Here you have already checked (line 69) that buffer is not NULL, this whole if is unnecessary

2022-09-28 06:03 UTC, LorenzoRuffati commented
If you start the receiver before the sender it fails
![image](https://user-images.githubusercontent.com/111505340/192700045-99a2de23-7adf-46e8-b388-8126a6fdea73.png)

If expected you should change the README since it specifies you can start programs in any order

2022-09-28 06:15 UTC, LorenzoRuffati requested changes
#4 Needs to be fixed before merging

2022-09-28 06:21 UTC, LorenzoRuffati commented on ipc_receivefile.c
> +		fd = open(info->file_name, O_RDWR | O_CREAT , 0660);
This is most likely what's causing #4

2022-09-28 09:39 UTC, LorenzoRuffati commented on ipc_receivefile.c
>  					"./ipcReceive -s <shared_name> -f <file_name>\n");
Sorry, just realized the diff acted weird, I mean the inner if and the printf

2022-09-28 11:29 UTC, giangle-unikie commented on ipc_receivefile.c
>  					"./ipcReceive -s <shared_name> -f <file_name>\n");
What is " the diff acted weird"?

2022-09-28 11:32 UTC, LorenzoRuffati commented on ipc_receivefile.c
>  					"./ipcReceive -s <shared_name> -f <file_name>\n");
It's highlighting the part of the code that I would not change, what I was saying is that the lines 21-26 could be handled by the options function

2022-09-28 12:13 UTC, giangle-unikie commented on ipc_common.c
> +void options(ipc *info, int argc, char *argv[]){
I already had the IPC struct in a header file and I don't think it is necessary to make one more inside function.

2022-09-28 12:19 UTC, LorenzoRuffati commented on ipc_common.c
> +void options(ipc *info, int argc, char *argv[]){
I'm not sure I understand, my suggestion was to allocate the "ipc" struct on the stack by returning an "ipc" value from options instead of allocating it on the heap through malloc and then modifying it via a pointer in "options"

2022-09-28 12:20 UTC, LorenzoRuffati commented on ipc_common.c
> +void options(ipc *info, int argc, char *argv[]){
But in any case it was just a style suggestion, the only thing blocking the PR for me is the bug in #4

2022-09-28 14:24 UTC, antonkraft reviewed
This is how I came so far. Since I am at the brink of implementing MQ as well, I think I can review better, after acquiring more knowledge for this topic.

2022-09-28 14:24 UTC, antonkraft commented on ipc_receivefile.c
> +	info = (ipc *) malloc (sizeof(ipc));
You can copy the NULL-handling from sender here. Or just comment, that it can be NULL here.

2022-09-28 14:24 UTC, antonkraft commented on ipc_sendfile.c
> +		if (fd == -1) {
find_file_size() is used on a fd, that may be -1, since you check for that afterwards, see my other comment.

2022-09-28 14:24 UTC, antonkraft commented on ipc_common.c
> +}
May receive -1 as `fd`. fstat() probably can handle this and most likely returns a -1 as well, but accessing the struct may result in a crash under those circumstances.

2022-09-28 14:40 UTC, giangle-unikie commented on README.md
> +Using Makefile to build system. After complie by 'make', the program will create 2 binaries: ipc_sendfile and ipc_receivefile.
Yes, After compilation by make

2022-09-28 14:45 UTC, giangle-unikie commented on ipc_receivefile.c
> +	info = (ipc *) malloc (sizeof(ipc));
I moved ipc malloc here to options function in the common.c and check NULL there.

2022-09-28 15:02 UTC, giangle-unikie commented on ipc_receivefile.c
> +	}
I think I can create hflag, and if hflag == 0 then no file is given. 
Is it the thing you mean?

2022-09-29 08:04 UTC, LorenzoRuffati commented on ipc_common.c
> +    if(fd != -1){
It'd be cleaner to check if fd is -1 immediately after obtaining the file descriptor and then assume that if this function is called the caller already checked fd is a valid file descriptor. 

But it's a minor observation, no change required

2022-09-29 08:07 UTC, LorenzoRuffati commented on ipc_receivefile.c
> +	ipc* info = options(argc, argv);
As in my previous comment, there's no need for info to be a pointer, it could be a simple stack variable and you'd save yourself the trouble of malloc-ing and free-ing, anyway the program seems correct, so no changes required

2022-09-29 08:12 UTC, LorenzoRuffati commented on ipc_common.h
> +    int hflag;
hflag is defined and then accessed but it is never assigned to. You might have forgotten to push some change to `options` that assigned to it

Needs to be fixed before merging (accessing an uninitialized variable is undefined behaviour)

2022-09-29 08:14 UTC, LorenzoRuffati commented on README.md
> +You can start receiver before sender or converse, because I set timeout for 7 seconds.
```suggestion
You can start receiver before sender or converse, the receiver will wait 7 seconds for the sender to start writing data to the queue before timing out.
```
I'd make it explicit that if you start the receiver before the sender you have only 7 seconds to start the sender

2022-09-29 08:26 UTC, LorenzoRuffati requested changes
hflag is declared and read but never assigned to, this needs to be fixed.

I would also add to the readme that the name of the queue needs to start with `/`

I added a note in the readme as well but the only blocker is the hflag, with that changed it looks good to be merged to me

2022-09-29 08:44 UTC, giangle-unikie commented on ipc_common.h
> +    int hflag;
ok, I forgot to make changes in options. I will do it.

2022-09-29 13:44 UTC, antonkraft commented on ipc_receivefile.c
> +	}
No, I mean if fflag==0, nothing happens. The whole if-block is skipped. Question is, do you want it to be this way ?

2022-09-29 13:47 UTC, antonkraft commented on ipc_common.c
> +}
Perhaps you know, how ftsat() reacts to -1 regarding the struct: NULL or empty values ?

2022-09-29 13:54 UTC, giangle-unikie commented on ipc_receivefile.c
> +	}
if fflag==0 then no file is given. But I test with fflag==0, it shows the result the same as hflag == 0. 
So I think it does not need to add  if fflag==0

2022-09-29 14:00 UTC, antonkraft commented on ipc_receivefile.c
> +	} else if (info->hflag == 0) {
Ok, nvm https://github.com/millavalio-Unikie/complex-copy/pull/2#discussion_r982456297

2022-09-29 14:00 UTC, antonkraft commented on ipc_receivefile.c
> +	}
Solved with 9392b1bd6900c463791dc1ebdc3fe01c08ac9d66, see comment.

2022-09-29 14:18 UTC, giangle-unikie commented on ipc_common.c
> +}
I read in manpage then the errno is EBADF: fd is bad.

2022-09-30 11:00 UTC, LorenzoRuffati approved these changes

2022-09-30 13:01 UTC, antonkraft reviewed
You can ignore all comments marked with »NB: I am probably commenting outdated code.«. I am just keeping them, to check myself what happened. Seems as if I somehow ended up reviewing a specific commit, though even Lorenzo's remarks at one point did not match the code either.
I am aborting this review and check, what I saw so far.

2022-09-30 13:09 UTC, antonkraft reviewed
Ok, I resolved my redundant comments and moved the still relevant ones into this review.

2022-09-30 13:09 UTC, antonkraft commented on ipc_sendfile.c
> +		file_size = find_file_size(fd);
As said somewhere else: fd may be -1 here. Not sure what will happen.

2022-09-30 15:06 UTC, giangle-unikie commented on ipc_sendfile.c
> +		file_size = find_file_size(fd);
I added if(fd == -1) below fd and remove if(fd == -1) in find_file_size() function. 
It shows perror("open")

2022-10-03 05:43 UTC, LorenzoRuffati commented on ipc_sendfile.c
> +				while (send < file_size)
An assignment operation returns the value of the left operand after the operation https://stackoverflow.com/questions/9514569/what-does-an-assignment-return

2022-10-03 11:48 UTC, antonkraft commented on ipc_common.c
> +}
Then it is possible to catch this case, before accessing the struct. You do not have to change this. Just be aware of this.

2022-10-03 13:31 UTC, antonkraft reviewed
Those are my comments for all files except ipc_receivefile. Since Send and Receive are similar code, you probably may copy some changes from Send to Receive. I can then take a look into Receive after your commit. Otherwise I may just mark the same lines there.

If you do not plan to do any changes anymore (because you want to do the other tasks), then say so and I will finish this review.

2022-10-03 13:31 UTC, antonkraft commented on ipc_sendfile.c
> +				mq = mq_open(info->method_name, O_CREAT  | O_WRONLY, 0666, NULL);
Double space (perhaps has no effect though)
```suggestion
				mq = mq_open(info->method_name, O_CREAT | O_WRONLY, 0666, NULL);
```

2022-10-03 13:31 UTC, antonkraft commented on ipc_sendfile.c
> +				}
```suggestion
				if (mq == -1)
				{
					perror("mq_open");
					free(info);
					exit(EXIT_FAILURE);
				}
```

2022-10-03 13:31 UTC, antonkraft commented on ipc_sendfile.c
> +				}
```suggestion
				if(buffer == NULL){
					perror("malloc");
					free(info);
					exit(EXIT_FAILURE);
				}
```

2022-10-03 13:31 UTC, antonkraft commented on ipc_sendfile.c
> +						exit(EXIT_FAILURE);
```suggestion
						perror("mq_send");
						free(info);
						free(buffer);
						exit(EXIT_FAILURE);
```

2022-10-03 13:31 UTC, antonkraft commented on ipc_sendfile.c
> +						}
```suggestion
						if(count == 10){
							printf("Can not send file.\n");
							mq_close(mq);
							mq_unlink(info->method_name);
							close(fd);
							free(info);
							exit(EXIT_FAILURE);
						}
```

2022-10-03 13:31 UTC, antonkraft commented on ipc_sendfile.c
> +				else
This block will currently only be active, when send > file_size
Note, that you are exiting the programme, when timedsend() returns with -1 (because of Timeout or other errors).

2022-10-03 13:31 UTC, antonkraft commented on ipc_sendfile.c
> +				}
```suggestion
				{
					printf("Connection lost. Interrupted transfer. Removed [%s]\n", info->method_name);
					mq_close(mq);
					mq_unlink(info->method_name);
					close(fd);
					free(info);
					exit(EXIT_FAILURE);
				}
```

2022-10-04 10:03 UTC, giangle-unikie commented on ipc_sendfile.c
> +				else
This block is active when send = file_size

2022-10-04 14:20 UTC, antonkraft commented on ipc_sendfile.c
> +				else
I am talking about the else-branch (Got also shows lines above the marked one).

2022-10-04 16:58 UTC, antonkraft commented on ipc_sendfile.c
> +				else
Ok, then you are aware of this. Fine by me.

2022-10-07 06:22 UTC, antonkraft commented
I will review, when the the conflicts are resolved.

2022-10-10 10:29 UTC, millavalio-Unikie commented
Created new pull request for merging #5

2022-10-10 10:29 UTC, closed without merging

2022-10-10 11:29 UTC, antonkraft commented on ipc_common.c
> +		exit(EXIT_FAILURE);
Unreachable code is fixed here.

2022-10-10 11:33 UTC, antonkraft commented on ipc_sendfile.c
> +			exit(EXIT_FAILURE);
Line moved.

2022-10-10 11:43 UTC, antonkraft commented
Resolved and unresolved comments based on #5.